# Generated by Django 3.2.6 on 2022-01-29 08:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('todoapiapps', '0002_todo'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='completed_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Ngày hoàn thành'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='todo',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='todoes', to=settings.AUTH_USER_MODEL, verbose_name='Người dùng'),
        ),
    ]
